export const peopleAdapterSpanish: Record<string, string> = {
  name: 'nombre',
  height: 'altura',
  mass: 'masa',
  hair_color: 'color_del_cabello',
  skin_color: 'color_de_piel',
  eye_color: 'color_de_ojos',
  birth_year: 'fecha_de_nacimiento',
  gender: 'genero',
  homeworld: 'planeta_natal',
  films: 'peliculas',
  species: 'especies',
  vehicles: 'vehiculos',
  starships: 'naves_espaciales',
  created: 'creado',
  edited: 'editado',
  url: 'url',
};
