export const planetAdapterSpanish: Record<string, string> = {
  name: 'nombre',
  rotation_period: 'periodo_de_rotacion',
  orbital_period: 'periodo_orbital',
  diameter: 'diametro',
  climate: 'clima',
  gravity: 'gravedad',
  terrain: 'terreno',
  surface_water: 'superficie_del_agua',
  population: 'poblacion',
  residents: 'residentes',
  films: 'peliculas',
  created: 'creado',
  edited: 'editado',
  url: 'url',
};
